# Generated by Django 6.0.5 on 2026-05-07 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trabajador', 'Trabajador de Oficio'), ('empleador', 'Empleador')], max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('oficios', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion_personal', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('rubro', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
