# Generated by Django 6.0.5 on 2026-05-07 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='anios_experiencia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='contactos_externos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fotos_portafolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='promedio_calificacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='perfil',
            name='total_calificaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('trabajador', 'Trabajador de Oficio'), ('empleador', 'Empleador')], max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(max_length=150),
        ),
    ]
