# Generated by Django 6.0.5 on 2026-05-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0005_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='modalidad',
        ),
    ]
