# Generated by Django 6.0.5 on 2026-05-08 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0007_servicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortafolioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
                ('trabajador', models.ForeignKey(limit_choices_to={'perfil__tipo': 'trabajador'}, on_delete=django.db.models.deletion.CASCADE, related_name='portafolio_fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', '-fecha_subida'],
            },
        ),
    ]
