# Generated by Django 6.0.5 on 2026-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficios', '0010_oferta_latitud_oferta_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
